version: '3'

# networks:
#   ros:
#     driver: bridge

services:
  ros-master:
    container_name: ros-master
    image: ros:noetic-ros-core
    command: stdbuf -o L roscore
    # networks:
    #   - ros
    network_mode: host
    restart: always
    ports:
      - "11311:11311"
  rosterm:
    image: tfm_noetic:latest
    container_name: rosterm
    network_mode: host
    environment:
      - "ROS_MASTER_URI=http://localhost:11311"
      -  DISPLAY
      -  NVIDIA_VISIBLE_DEVICES=all
      -  NVIDIA_DRIVER_CAPABILITIES=all
      -  QT_X11_NO_MITSHM=1
    user: ${UGID} 
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority?:ro
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /home/${USER}:/home/${USER}:rw 
      - /dev:/dev
    restart: always
    stdin_open: true
    tty: true
    privileged: true
    
  