version: '3'

networks:
  ros:
    driver: bridge

services:
  # ros-master:
  #   container_name: ros-master
  #   image: ros:noetic-ros-core
  #   command: stdbuf -o L roscore
  #   networks:
  #     - ros
  #   restart: always
  #   ports:
  #     - "11311:11311"

  rosterm:
    image: tfm_noetic:latest
    container_name: rosterm
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        USER: ${USER}
    # depends_on:
    #   - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://tiago-162c:11311"
      -  DISPLAY
      -  NVIDIA_VISIBLE_DEVICES=all
      -  NVIDIA_DRIVER_CAPABILITIES=all
      -  QT_X11_NO_MITSHM=1 #fix some QT bugs
    #share your user to the container in order to access your x11
    user: ${UGID} #adapt as needed!
    volumes: 
      #share your x11 socket and permissions to the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority?:ro
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      # - /etc/sudoers:/etc/sudoers:ro
      # - /etc/sudoers.d:/etc/sudoers.d:ro
      - /home/${USER}:/home/${USER}:rw #share your home with write permissions
    restart: always
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
